Rails.application.routes.draw do
  get 'subscriptions/index'
  get 'subscriptions/show'
  get 'subscriptions/new'
  get 'subscriptions/create'
  get 'subscriptions/destroy'
  get 'memberships/index'
  get 'memberships/show'
  get 'memberships/new'
  get 'memberships/create'
  get 'memberships/destroy'
  get 'documents/index'
  get 'documents/show'
  get 'documents/new'
  get 'documents/create'
  get 'documents/destroy'
  get 'documents/search'
  get 'conversations/index'
  get 'conversations/show'
  get 'conversations/new'
  get 'conversations/create'
  get 'conversations/edit'
  get 'conversations/update'
  get 'conversations/destroy'
  get 'families/index'
  get 'families/show'
  get 'families/new'
  get 'families/create'
  get 'families/edit'
  get 'families/update'
  get 'families/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
